### PR TITLE
Allow for POST consent request

### PR DESCRIPTION
**Pull request by mrvanes**
Allow for POST consent request. 4K is too small for large attribute sets/values

### CODE REVIEW

**Comment by c00kiemon5ter** [comment]
@rohe ping. Can you please merge this?

**Comment by rohe** [comment]
OK, the tests are failing but I trust you to know what you're doing :-)
I'm just your proxy :-)

**Comment by mrvanes** [comment]
Thx for merging @rohe 

As far as I understand the travis logs, no testbuild will succeed anymore
```
...
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
...
tox.InvocationError: InvocationError for command /home/travis/build/its-dirg/CMservice/.tox/py34/bin/pip freeze (see /home/travis/build/its-dirg/CMservice/.tox/py34/log/py34-3.log) (exited with code 1)
...
The command "tox" exited with 1.
```

**Comment by c00kiemon5ter** [comment]
This seems to be a problem with `pyopenssl`. Seems to be fixed if we replace pyopenssl dependency version in [`test_requirements.txt`](https://github.com/its-dirg/CMservice/blob/01363ff/tests/test_requirements.txt)

```diff
-pyopenssl==16.0.0
+pyopenssl==16.2.0
```

**Comment by rohe** [comment]
OK, can do that tomorrow.

**Pull request merged**
